FROM dunglas/frankenphp

ENV FRANKENPHP_CONFIG="worker ./public/index.php"
ENV APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime
ENV SERVER_NAME=denz.ovh
ENV APP_ENV=prod
ENV APP_DEBUG=0

RUN install-php-extensions \
  pdo_mysql \
  gd \
  intl \
  zip \
  opcache \
  apcu

WORKDIR /app
