services:
    php:
        build:
            context: .
            dockerfile: ${DOCKERFILE:-Dockerfile}
        container_name: frankenphp
        restart: always
        ports:
            - "8080:80"
            - "443:443"
            - "443:443/udp"
        networks:
            - sf-network
        volumes:
            - ./:/app
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            - DATABASE_URL=mysql://root:symfonycda@mysql:3306/symfonycda
        depends_on:
            - mysql
        tty: true

    mysql:
        image: mysql:8.0.32
        restart: always
        container_name: mysql
        environment:
            MYSQL_DATABASE: symfonycda
            MYSQL_ROOT_PASSWORD: symfonycda
        ports:
            - "33336:3306"
        networks:
            - sf-network
        volumes:
            - database_data:/var/lib/mysql:rw

    mailer:
        image: mailhog/mailhog:latest
        container_name: mailer
        restart: always
        ports:
            - "1025:1025" # SMTP
            - "8025:8025" # Web UI
        networks:
            - sf-network

volumes:
    caddy_data:
    caddy_config:
    database_data:

networks:
    sf-network:
        driver: bridge
